server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: 123456
    min-idle: 5
    initial-size: 1
    max-idle: 15

  application:
    name:  microservicecloud-dept80-consumer

eureka:
  client:
    service-url:
      defaultZone:  http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka,http://eureka7004.com:7004/eureka
  instance:
    instance-id: microservicecloud-dept80-consumer
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true


